Tugas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib.auth import views
"""from programs import views"""

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Tugas1.urls')),
    path('programs/', include('programs.urls')),
    path('donation/', include('donationform.urls')),
    path('news/', include('news.urls')),
    path('registration/', include('registration.urls')),
    path('about/', include('about.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('auth/', include('social_django.urls', namespace='social')),
	path('dashboard/', include('dashboard.urls'))
]

Tugas1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'Tugas1'

urlpatterns = [
        path('', views.index, name='index'),
	path('index', views.index, name='index'),
        path('landingnews/<str:namaberita>',views.landing, name='namaberita'),
        path('logout', views.logout_view , name='logout'),
]

donationform/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.form, name='namaprogram'),
    path('donation_added/', views.donate),
    path('<str:namaprogram>/', views.form, name='namaprogram'),
]

news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name = 'index'),
    path('<str:namaberita>/' , views.index, name = 'namaberita')
]

donationform/models.py
from django.db import models
from django.contrib.auth.models import User
from programs.models import Program

# Create your models here.
class Donation(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    program = models.ForeignKey(Program, on_delete=models.CASCADE, null=True, blank=True)
    # program = models.CharField(max_length=300, default='')
    # firstname = models.CharField(max_length=300, default='Anonymous')
    # lastname = models.CharField(max_length=300, default='Anon')
    # email = models.CharField(max_length=300, default='anon@mail.com')
    amount = models.DecimalField(decimal_places=1, max_digits=20, default=0)
    # showname = models.BooleanField(default=True)

    def __str__(self):
        if (self.user == None):
            return "Anonymous"


        return self.user.username + ' untuk ' + self.program.title

donationform/forms.py
from django import forms

class DonationForm(forms.Form):

    # firstname = forms.CharField(widget=forms.TextInput({'class' : 'form-control', 'placeholder' : 'Front Name'}))
    # lastname = forms.CharField(widget=forms.TextInput({'class' : 'form-control', 'placeholder' : 'Last Name'}))
    # email = forms.CharField(widget=forms.TextInput({'class' : 'form-control', 'placeholder' : 'john@mail.com'}))
    amount = forms.DecimalField(widget=forms.NumberInput({'class' : 'form-control','placeholder' : 'Enter Amount'}))
    # showname = forms.BooleanField(widget=forms.CheckboxInput({'class' : 'form-control'}), required=False)

donationform/views.py
from django.forms import model_to_dict
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from .forms import DonationForm
from .models import Donation
from programs.models import Program
from registration.models import RegistrationBack

# Create your views here.

# Webservice yang return semua donasi yang pernah dilakukan oleh user
'''
Bentuknya : 

{"data": [{"program_title": "Palu", "amount": 3700}, {"program_title": "Palu", "amount": 3000},
          {"program_title": "Palu", "amount": 200}, {"program_title": "Palu", "amount": 3006}]}
'''

def donation_list_service(request):
    # return json semua donasi yang pernah dilakukan user
    #
    if not request.user.is_authenticated:
        return HttpResponse("<h1> Not Allowed <h1>")

    data_banyak = list(request.user.donation_set.all())

    data = [] # Bentuknya List
    jeson = {} # Dictionary
    for i in range(len(data_banyak)):
        masuk_ke_simpan = {'program_title': data_banyak[i].program.title, 'amount': int(data_banyak[i].amount)}
        data.insert(i, masuk_ke_simpan)

    jeson['data'] = data

    return JsonResponse(jeson, safe=False)


def form(request, namaprogram):
    form = DonationForm()
    data = Program.objects.all()

    masuk = Program.objects

    for i in data:
        if i.link.lower() == namaprogram.lower():
            masuk = i
            break

    response = {'form': form, 'program': masuk, 'user': request.user}
    return render(request, 'donation.html', response)


response = {}


def donate(request):
    user = request.user

    if request.method == 'POST':
        form = DonationForm(request.POST or None)
        if form.is_valid():
            response['program'] = Program.objects.filter(title=request.POST['program'])[0]
            response['amount'] = request.POST['amount']

            print(type(request.POST['program']))
            donation = Donation(user=user, program=response['program'], amount=response['amount'])
            donation.save()
            return render(request, 'donation_added.html', response)

    else:
        return render(response, 'donation_form_invalid.html')

donationform/templates/donation.html
{% extends 'basenew.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'donationform/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}


{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-8">


                <!-- Navbar -->
                <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color:#242424">
                    <a class="navbar-brand" href=""><img src="{% static 'img/logo.png' %}" width="30" height="30"
                                                         class="d-inline-block align-top" alt=""></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarNavAltMarkup"
                            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <ul class="navbar-nav mr-auto">

                            <a class="nav-item nav-link active" href="/">Home<span class="sr-only">(current)</span></a>
                            <a class="nav-item nav-link active" href="/programs">Programs <span
                                    class="sr-only">(current)</span></a>
                            <a class="nav-item nav-link active" href="/about">About Us <span
                                    class="sr-only">(current)</span></a>

                        </ul>

                        {%if user.is_authenticated%}
                        <ul class="navbar-nav ml-auto">
                            <li><a class="nav-item nav-link active" href="/dashboard">{{user.username}}</a></li>
                            <li><a href= "{% url 'Tugas1:logout'%}" style="text-transform:none; margin-top: 3%;">
                                    <button class="btn button-sinar-perak">
                                            Logout</button></a></li>
                        </ul>
                        {%else%}
                        <ul class="navbar-nav ml-auto ">
                            <a href="{% url 'social:begin' 'google-oauth2' %}" style="text-transform:none">
                            <button class="btn button-sinar-perak">
                                <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
                                Login</button></a>
                        </ul>
                        {%endif%}
                    </div>
                </nav>
                <!-- End of Navbar -->

                <div class="content-and-form">
                    <h1 id="judul-content">{{ program.title }}</h1>
                    <br>

                    <div class="form-row marginform">
                        <section name="form">
                            <form id="form" method="POST" action="/donation/donation_added/">
                                {% csrf_token %}

                                <div class="form-group">

                                    <label>How much do you want to give?</label>
                                    <div class="row">
                                        <br>
                                        <div class="col">
                                            {{ form.amount }}
                                        </div>
                                    </div>


                                    <br>

                                    <input type="hidden" name="program" value="{{ program.title }}" />
                                    <button type="submit" class="btn button-sinar-perak">Submit</button>
                                </div>
                            </form>
                        </section>
                    </div>
                </div>

            </div>


            <div class="col-sm-4">
                <img class="foto-kanan" src="{{ program.imgsrc }}">
                <!-- <img class="foto-kanan" src="http://placekitten.com/500/800"> -->

                <div class="footer-hijau">

                    <h1 class="judul-program">"{{ program.title }}"</h1>
                    <hr>
                </div>
            </div>
        </div>
    </div>





{% endblock %}

donationform/templates/donation_added.html
<!DOCTYPE html>
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CDN -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<!--               -->

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/sinarPerakFavicon.png' %}"/>
    <title>Sinar Perak Foundation</title>
    <title>Sinar Perak</title>
</head>

<body class="body-index" background="{% static 'img/bakcgroundLanding.png' %}">
<div class="layer-landing container-fluid">
    <p style="margin: 0;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    color: white;
    font-family: 'Open Sans', sans-serif;
    font-size: 2rem;
    font-style: italic;
    text-align: center"> Donation Sent!
    <br>
    <a href="/programs"><button class="btn button-sinar-perak">Back to Programs</button></a></p>
    
  </div>


</div>

</body>
</html>

donationform/templates/donation_form_invalid.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

donationform/templates/donation_not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Donation Doesnt Exist</h1>

</body>
</html>

donationform/templates/user_not_found.html
<!DOCTYPE html>
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CDN -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<!--               -->

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/sinarPerakFavicon.png' %}"/>
    <title>Sinar Perak Foundation</title>
    <title>Sinar Perak</title>
</head>


<body class="body-index" background="{% static 'img/bakcgroundLanding.png' %}">


<script>
    function goBack() {
        window.history.back();
    }
</script>


<div class="layer-landing container-fluid">
    <p style="margin: 0;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    color: white;
    font-family: 'Open Sans', sans-serif;
    font-size: 2rem;
    font-style: italic;
    text-align: center"> Email Not Found
        <br>
        <button onclick="goBack()" class="btn button-sinar-perak">Go Back</button>
    </p>

</div>


</div>

</body>
</html>